"""ai-orchestrator-client — Python SDK for the AI Orchestrator HTTP API."""

from ._auth import AuthProvider, BearerTokenAuth
from ._errors import (
    NotFound,
    OrchestratorAPIError,
    OrchestratorError,
    ProjectNameInvalidError,
    RunFailed,
    ServiceUnavailable,
    UnknownCapabilityError,
    ValidationError,
    WaitInterrupted,
    WaitTimeout,
)
from .async_client import AsyncOrchestratorClient
from .consumer import Consumer, Hindsight, Ntfy, Vault, capability
from .models import (
    Campaign,
    CampaignAck,
    CampaignControlAck,
    CampaignCreate,
    CampaignRun,
    CampaignStatus,
    CampaignTemplate,
    CampaignTreeRun,
    CampaignTreeView,
    CampaignVerifyResult,
    CapabilityInvokeResult,
    ConsumerAck,
    ConsumerRecord,
    ConsumerRegistration,
    EvidencePush,
    HealthReport,
    LogEvent,
    ManifestStatus,
    MemoryWrite,
    Notification,
    OrchestrateAck,
    OrchestrateRequest,
    OrchestrateResult,
    RunningResult,
    RunPhase,
    RunStatus,
    RunVerifyResult,
    StatusEvent,
    VaultNote,
)
from .sync_client import OrchestratorClient

__version__ = "0.1.1"

__all__ = [
    "__version__",
    # clients
    "AsyncOrchestratorClient",
    "OrchestratorClient",
    # auth
    "AuthProvider",
    "BearerTokenAuth",
    # consumer integration (Phase 3.6)
    "Consumer",
    "Hindsight",
    "Ntfy",
    "Vault",
    "capability",
    # errors
    "NotFound",
    "OrchestratorAPIError",
    "OrchestratorError",
    "ProjectNameInvalidError",
    "RunFailed",
    "ServiceUnavailable",
    "UnknownCapabilityError",
    "ValidationError",
    "WaitInterrupted",
    "WaitTimeout",
    # models
    "Campaign",
    "CampaignAck",
    "CampaignControlAck",
    "CampaignCreate",
    "CampaignRun",
    "CampaignStatus",
    "CampaignTemplate",
    "CampaignTreeRun",
    "CampaignTreeView",
    "CampaignVerifyResult",
    "CapabilityInvokeResult",
    "ConsumerAck",
    "ConsumerRecord",
    "ConsumerRegistration",
    "EvidencePush",
    "HealthReport",
    "LogEvent",
    "ManifestStatus",
    "MemoryWrite",
    "Notification",
    "OrchestrateAck",
    "OrchestrateRequest",
    "OrchestrateResult",
    "RunPhase",
    "RunStatus",
    "RunVerifyResult",
    "RunningResult",
    "StatusEvent",
    "VaultNote",
]
